app = 'heylow'
primary_region = 'ams'

[env]
  NODE_ENV = "production"
  WORLD = "world"
  PORT = "3000"
  JWT_SECRET = "hyper"
  ADMIN_CODE = "qwerty"
  SAVE_INTERVAL = "60"
  PUBLIC_MAX_UPLOAD_SIZE = "12"
  PUBLIC_WS_URL = "https://heylow.fly.dev/ws"
  PUBLIC_API_URL = "https://heylow.fly.dev/api"
  PUBLIC_ASSETS_URL = "https://heylow.fly.dev/assets"

[mounts]
  source = 'data'
  destination = '/app/world'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1